# Generated by Django 3.2.13 on 2022-12-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('scrape', models.BooleanField(default=False)),
                ('date_scrape', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
