# Generated by Django 3.2.13 on 2022-12-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='bats',
        ),
        migrations.AddField(
            model_name='results',
            name='bath',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='association_fee',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='beds',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='image_links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='lot_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='lot_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='mls_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='parking_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='postal_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='property_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='sqft',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='sub_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
